### ISSUE TITLE
null values and addConcreteSettersForOptional

### ISSUE THREAD

**Issue by lpandzic** [Randgalt/record-builder#107]
I find that addConcreteSettersForOptional uses `Optional#of` instead of `Optional#ofNullable` quite surprising especially since Intellij IDEA by default doesn't warn against passing nulls to `javax.validation.constraints.NotNull` annotated parameters.
What is the reasoning behind this decision?

**Comment by Randgalt** [comment]
Yeah - I think that might be a mistake. I see no reason why it shouldn't be `ofNullable()`.

**Comment by lpandzic** [comment]
@mads-b I see you are the https://github.com/Randgalt/record-builder/pull/95 author, is this a bug or intentional?

**Comment by mads-b** [comment]
@lpandzic it is intentional, but feel free to change it.

My reasoning is that if you have nulls you shouldn't be calling the setter at all; you should know whether your value is nullable or not. That being said, there is no harm in just tolerating it in the library code like you suggest.

**Comment by agentgt** [comment]
> since Intellij IDEA by default doesn't warn against passing nulls to javax.validation.constraints.NotNull annotated parameters.

Just a  clarification for @lpandzic and @mads-b you really really should not use `javax.validation.constraints.NotNull` annotation for null analysis and that is probably why intellij doesn't do anything.

The javax.validation is designed for validation. They values are expected to be possibly null. Before the object is validated the values could be null!

Null analysis on the other hand is an invariant and is type based. Thats why you should either use JSpecify or Checker or Eclipses annotations as they are TYPE_USE annotations. That is why #106 is important to fix.

@Randgalt  [it doesn't even make since to have methods with javax.validation.constraints (your gist you shared on reddit showing full builder)](https://gist.github.com/Randgalt/8aa487a847ea2acdd76d702f7cf17d6a#file-fullrecordbuilder-java-L41) unless you immediately call the validator. In fact the [requireNonNull on justAString is wrong](https://gist.github.com/Randgalt/8aa487a847ea2acdd76d702f7cf17d6a#file-fullrecordbuilder-java-L45) as well as the previous lines. It should throw constraint validation exception. The other two parameters are `@Nullable` and should be marked as that.

To be honest a record isn't the ideal use case for using validation. It's actually the builder. A web request or whatever fills the builder and then when you build the record the builder is validated makes sure record has all the invariants likes not null.

**Comment by lpandzic** [comment]
> Just a clarification for @lpandzic and @mads-b you really really should not use javax.validation.constraints.NotNull annotation for null analysis and that is probably why intellij doesn't do anything.

I'm not using it - I'm using the fact that IDEA lacks inference for bean validation @NotNull  as an example of why current Optional handing doesn't make sense.

On the topic of whether bean validation @NotNull should be separate from one of many null inference annotation inference libraries is a debatable question. Whether we should be using Optionals in non jdk libraries is a even more debatable question.
My opinion on the matter is that once they introduce inline types (or value types as they were known back in 2013/2014...) they should make Optional a non nullable inline type and this nullness check annotations problem can go away and we can stop wasting time on this.

> To be honest a record isn't the ideal use case for using validation. It's actually the builder. A web request or whatever fills the builder and then when you build the record the builder is validated makes sure record has all the invariants likes not null.

I disagree. Invariants should be both documented and validated against records and not builders. Records are single source of truth for fields and properties of those fields. Whether a builder validates anything is and should be a configurable option and not a requirement. Any larger codebase with larger API surface cannot guarantee that builders are always used (e.g. external developers). If an external developer creates a record directly what happens then? Is validation done twice?

Anyway, I believe this side story is a topic for another issue. I'd like to focus on changing the Optional handling in this issue.
@Randgalt can you please review the PR?

**Comment by agentgt** [comment]
> I'm not using it - I'm using the fact that IDEA lacks inference for bean validation https://github.com/NotNull as an example of why current Optional handing doesn't make sense.

Maybe you can clarify that some more since I'm working on the other issue. I don't want to impact it. What inference are we talking about that isn't null analysis? Some completion? I haven't used IntelliJ in a year.

> I disagree. Invariants should be both documented and validated against records and not builders. Records are single source of truth for fields and properties of those fields. Whether a builder validates anything is and should be a configurable option and not a requirement. Any larger codebase with larger API surface cannot guarantee that builders are always used (e.g. external developers). If an external developer creates a record directly what happens then? Is validation done twice?

Well thats the thing they are not really invariants like types. I don't really care what people's interpretation of the annotations is so long as your not using them for null analysis (you should not) but they are not TYPE_USE annotations.

The java validation mostly is used for this workflow. You have a HTML form presented on a GET request. Your  model is an object that has validation annotations is either completely blank or partially filled. The object that gets put in the model is often largely not valid. Then you run validation. If you don't run validation first then you could get a null pointer exception instead of a constraint violation exception.

If you do magical AspectJ or whatever byte weaving magic where you validate on constructing I guess I could see but I largely disagree with using them as "invariant" like types. 

> Any larger codebase with larger API surface cannot guarantee that builders are always used (e.g. external developers). If an external developer creates a record directly what happens then? Is validation done twice?

You can certainly use records with validation annotations but the expectation is you will be creating an invalid objects all the time... and usually not fail immediately like a null pointer exception. This is completely separate from null analysis.

> My opinion on the matter is that once they introduce inline types (or value types as they were known back in 2013/2014...) they should make Optional a non nullable inline type and this nullness check annotations problem can go away and we can stop wasting time on this.

Assuming Valhalla does come in the next 5 years (which we will be lucky if loom comes in that time frame) we still have 20 or more years of code bases that can easily be annotated without breaking compile time including the JDK (e.g. Map.get isn't going to be changed to return Optional). Loom largely will not break existing libraries but trying to retrofit everyone to use Optional will. Besides null will still exist.

The only reason I make a big deal out of the validation annotations is to get folks at least use proper annotations and this does not include javax.validation or the findbugs annotations. If people did we might have JSpecify or something like it widespread but we can't if you use validation annotations for null analysis or we just assume the JDK will fix it. 

Anyway its probably all moot because I assumed you were doing null analysis but if intelliJ does something else then you can clearly ignore me.

**Comment by Randgalt** [comment]
> @Randgalt [it doesn't even make since to have methods with javax.validation.constraints (your gist you shared on reddit showing full builder)](https://gist.github.com/Randgalt/8aa487a847ea2acdd76d702f7cf17d6a#file-fullrecordbuilder-java-L41) unless you immediately call the validator. In fact the requireNonNull on justAString is wrong

Wrong is a loaded term here. As I recall we were trying to emulate what the Immutables library does and, again as I recall, it treats any non-null-like annotation as implying a null check. The goal of the library is utility so while it may not conform to a particular spec it does conform to those who wish to migrate from the Immutables library. If there's a strong desire to conform to a different spec that can be done via another option but I'd like to see a community desire for this.

**Comment by agentgt** [comment]
Can you provide a link of that behavior because the [behavior I'm proposing of focusing on `@Nullable` is what immutables seems to be doing not `@No[tN]Null`](https://immutables.github.io/immutable.html#nullable-attributes)


Now let us go look at your gist again.


```
    @Generated("io.soabase.recordbuilder.core.RecordBuilder")
    public static FullRecord FullRecord(@NotNull List<Number> numbers,
            @NotNull Map<Number, FullRecord> fullRecords, @NotNull String justAString) {
        numbers = __list(numbers);
        fullRecords = __map(fullRecords);
        Objects.requireNonNull(justAString, "justAString is required");
        return new FullRecord(numbers, fullRecords, justAString);
    }
```

`__list` and `__map`` coerce nulls to empty collections and not just any empty collections but special immutable ones that will fail of you do something like `contains(null)` (regular ArrayList does not do this). Why not fail fast here? The irony is you just made the contract actually

```
    public static FullRecord FullRecord(@Nullable List<Number> numbers,
            @Nullable Map<Number, FullRecord> fullRecords, @NotNull String justAString) {
````


Then you arbitrarily decide that Strings on the other hand cannot be coerced. That null cannot be coerced to an empty string.

I'll go check but I doubt Immutables does the above.

It just seems like the `NotNull` behavior needs some rethinking and was added way too quickly to this library. Especially so if you are trying to mimic immutables. Also given that the last three issues that are currently open have to do with nonnull it clearly has some issues even in the community.

**Comment by agentgt** [comment]
Let us say I have a record that has an Optional and as an extra but not requirement lets say I am doing null analysis where the default is nonnull (that is only nullable is marked. I stress analysis and not inference like you are saying).

In my code I expect this to fail fast with a null pointer exception:

```
someSetter(null);
```

I might even have a unit test to expect that behavior. It certainly will get kicked on if mutation testing is done. So hopefully you only break peoples unit tests with your change.

Now for the null analysis without it being marked this method appears to be:

```
someSetter(@NonNull SomeType argument)
```

And indeed that was the original contract. Thus your change will never be seen and possibly misunderstood as well debatable breaking the contract.

Furthermore its confusing. If you are following the `Optional` paradigm of preventing null you wrap it immediately in `Optional`. Otherwise you are in the annotation paradigm house or you just don't care which we can ignore that latter case for now.

Maybe if the setter gets prefixed with `someSetterNullable` or `maybeSomeSetter` it might be better and we add `@Nullable` to the parameter. But is it really worth it when you can and really should be doing `ofNullable` or your own explicitly?

Speaking of which `ofNullable` is often considered bad practice (as well as `get` but I disagree on that one). I'll have to find the links but I remember even Brian mentioning it at some point. Some of it is stupid things like breaking monad rules but I believe there were some good points.  


Finally let's not forget why this whole issue was brought up in the first place. You assumed that `javax.validation.NotNull` would prevent you from passing null which was caused in my opinion by another issue (basing nonnull on a notnull annotation regex) and not that the setter should be nullable. Do you want that fixed (albeit with the proper annotations) or do you just want more `@Nullable` stuff exposed? I'm saying if you want to avoid null there should be less of that.

**Comment by agentgt** [comment]
@lpandzic Immutables which apparently is what this library is so supposed to emulate does not do what you want.

```java
import org.immutables.value.Value;

@Value.Immutable
public interface Stuff {
	Optional<String> someString();
}
```



```
  @Generated(from = "Stuff", generator = "Immutables")
  public static final class Builder {
    private String someString;

  //snip

    /**
     * Initializes the optional value {@link Stuff#someString() someString} to someString.
     * @param someString The value for someString
     * @return {@code this} builder for chained invocation
     */
    public final Builder someString(String someString) {
      this.someString = Objects.requireNonNull(someString, "someString");
      return this;
    }
```


See how this "reasonable" PR can lead to many more issues than you might think.

**Comment by Randgalt** [comment]
Can we pause this discussion for a bit please? When I get some more time I'll look into this deeper. I feel confident there's a good solution here that can meet everyone's needs.

**Comment by agentgt** [comment]
Yes that will probably be good for all. However I can't keep working on #106 or the other nullable annotation bugs till some decisions are made. Which is why I have been so back and forth on this as there are some serious previous design decisions that are impacting me.

So I'm fine with holding off indefinitely till some decisions are made (like lets copy what immutables does).

And I'm sorry for coming off rough and flooding the inbox but I have already sunken some time on this (a lot more than just changing some call from `of` to `ofNullable`) as I sort of felt obligated given previous discussions on reddit and whatnot.

I'll stop work and commenting till the dust clears.
